version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - FASTAPI_URL=${FASTAPI_URL}
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    restart: always
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=${FASTAPI_URL}
    env_file:
      - .env
    depends_on:
      - fastapi
    volumes:
      - .:/app
    command: streamlit run app.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
